export const FETCH_FILE_CONTENT_REQUEST = "FETCH_FILE_CONTENT_REQUEST";
export const FETCH_FILE_CONTENT_SUCCESS = "FETCH_FILE_CONTENT_SUCCESS";
export const FETCH_FILE_CONTENT_FAILURE = "FETCH_FILE_CONTENT_FAILURE";
